version: '3.7'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tectonic
        volumes:
            - .mysqldata:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

    app:
        build: .
        command: node build/main.js
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
        depends_on:
            - db
