version: '3.7'
services:
    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tectonic
        volumes:
            - .mysqldata:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        restart: always
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1

    app:
        build: .
        command: node build/main.js
        env_file:
            - .env
        environment:
            DATABASE_URL: mysql://root:root@db:3306/tectonic?schema=public
        depends_on:
            - db
