version: '3.7'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: tectonic
        volumes:
            - .pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: root@root.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - .pgadmin:/var/lib/pgadmin/data
        ports:
            - 5050:80

    app:
        build: .
        command: node build/main.js
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
        depends_on:
            - db
