import { type Client, ActivityType } from "discord.js";

export function startStatusRotation(bot: Client) {
	const activities: {
		name: string;
		type: Exclude<ActivityType, ActivityType.Custom>;
	}[] = [
			{ name: "OSRS", type: ActivityType.Playing },
			{ name: "99s", type: ActivityType.Competing },
			{ name: "RuneScape streams", type: ActivityType.Watching },
			{ name: "Sea Shanty 2", type: ActivityType.Listening },
			{ name: "in Gielinor", type: ActivityType.Playing },
			{ name: "the GE prices", type: ActivityType.Watching },
			{ name: "raids", type: ActivityType.Competing },
			{ name: "Old School RuneScape", type: ActivityType.Playing },
			{ name: "Zulrah guides", type: ActivityType.Watching },
			{ name: "medieval music", type: ActivityType.Listening },
			{ name: "in the Wilderness", type: ActivityType.Playing },
			{ name: "pets", type: ActivityType.Competing },
			{ name: "PKers rage quit", type: ActivityType.Watching },
			{ name: "Flute Salad", type: ActivityType.Listening },
			{ name: "at Barrows", type: ActivityType.Playing },
			{ name: "fight caves", type: ActivityType.Competing },
			{ name: "noobs die to cows", type: ActivityType.Watching },
			{ name: "Harmony", type: ActivityType.Listening },
			{ name: "Chambers of Xeric", type: ActivityType.Playing },
			{ name: "maxing", type: ActivityType.Competing },
			{ name: "GIM series", type: ActivityType.Watching },
			{ name: "Newbie Melody", type: ActivityType.Listening },
			{ name: "at Wintertodt", type: ActivityType.Playing },
			{ name: "in DMM", type: ActivityType.Competing },
			{ name: "B0aty highlights", type: ActivityType.Watching },
			{ name: "Autumn Voyage", type: ActivityType.Listening },
			{ name: "Theatre of Blood", type: ActivityType.Playing },
			{ name: "the Inferno", type: ActivityType.Competing },
			{ name: "RNG compilation", type: ActivityType.Watching },
			{ name: "Book of Spells", type: ActivityType.Listening },
			{ name: "Tempoross", type: ActivityType.Playing },
			{ name: "in LMS", type: ActivityType.Competing },
			{ name: "quest guides", type: ActivityType.Watching },
			{ name: "Scape Main", type: ActivityType.Listening },
			{ name: "at the Duel Arena", type: ActivityType.Playing },
			{ name: "PvP montages", type: ActivityType.Watching },
			{ name: "Background", type: ActivityType.Listening },
			{ name: "Nightmare", type: ActivityType.Competing },
			{ name: "for Twisted Bow", type: ActivityType.Watching },
			{ name: "Blast Furnace", type: ActivityType.Playing },
			{ name: "for skilling pets", type: ActivityType.Watching },
			{ name: "skill progress videos", type: ActivityType.Watching },
			{ name: "Morytania music", type: ActivityType.Listening },
			{ name: "at Pest Control", type: ActivityType.Playing },
			{ name: "clue scrolls", type: ActivityType.Competing },
			{ name: "HCIM deaths", type: ActivityType.Watching },
			{ name: "Forever", type: ActivityType.Listening },
			{ name: "Blast Furnace", type: ActivityType.Playing },
			{ name: "for a sigil drop", type: ActivityType.Playing },
			{ name: "quest speedruns", type: ActivityType.Watching },
			{ name: "Al Kharid theme", type: ActivityType.Listening },
			{ name: "at Guardians of the Rift", type: ActivityType.Playing },
			{ name: "for rune pouches", type: ActivityType.Playing },
			{ name: "OSRS memes", type: ActivityType.Watching },
			{ name: "Darkmeyer music", type: ActivityType.Listening },
			{ name: "Castle Wars", type: ActivityType.Playing },
			{ name: "for dragon claws", type: ActivityType.Playing },
			{ name: "PvM guides", type: ActivityType.Watching },
			{ name: "Yanille theme", type: ActivityType.Listening },
			{ name: "at Soul Wars", type: ActivityType.Playing },
			{ name: "elite clues", type: ActivityType.Competing },
			{ name: "RuneScape podcasts", type: ActivityType.Watching },
			{ name: "Edgeville theme", type: ActivityType.Listening },
			{ name: "Fight Caves", type: ActivityType.Playing },
			{ name: "champion scrolls", type: ActivityType.Competing },
			{ name: "drop logs", type: ActivityType.Watching },
			{ name: "Legends’ Guild music", type: ActivityType.Listening },
			{ name: "at Fishing Trawler", type: ActivityType.Playing },
			{ name: "XP waste", type: ActivityType.Competing },
			{ name: "PK tournament streams", type: ActivityType.Watching },
			{ name: "Fanfare 3", type: ActivityType.Listening },
			{ name: "Tombs of Amascut", type: ActivityType.Playing },
			{ name: "for purple chest", type: ActivityType.Playing },
			{ name: "Desert treasure music", type: ActivityType.Listening },
			{ name: "at Nex", type: ActivityType.Playing },
			{ name: "for Torva", type: ActivityType.Playing },
			{ name: "max efficiency guides", type: ActivityType.Watching },
			{ name: "Camelot theme", type: ActivityType.Listening },
			{ name: "Phosani's Nightmare", type: ActivityType.Playing },
			{ name: "for Harmonised orb", type: ActivityType.Playing },
			{ name: "ironman progression", type: ActivityType.Watching },
			{ name: "Lullaby", type: ActivityType.Listening },
			{ name: "Gauntlet", type: ActivityType.Playing },
			{ name: "speedrun records", type: ActivityType.Watching },
			{ name: "Prifddinas music", type: ActivityType.Listening },
			{ name: "Corrupted Gauntlet", type: ActivityType.Playing },
			{ name: "for enhanced seed", type: ActivityType.Playing },
			{ name: "GIM endgame series", type: ActivityType.Watching },
			{ name: "Elven Seed", type: ActivityType.Listening },
			{ name: "Chambers CM", type: ActivityType.Playing },
			{ name: "for pet Olmlet", type: ActivityType.Playing },
			{ name: "raid splitting guides", type: ActivityType.Watching },
			{ name: "The Depths", type: ActivityType.Listening },
			{ name: "Theatre HM", type: ActivityType.Playing },
			{ name: "for scythe", type: ActivityType.Playing },
			{ name: "ToB wipe compilations", type: ActivityType.Watching },
			{ name: "Medieval", type: ActivityType.Listening },
			{ name: "Colosseum", type: ActivityType.Playing },
			{ name: "for echo crystals", type: ActivityType.Playing },
			{ name: "PvM clan events", type: ActivityType.Watching },
			{ name: "Forthos Dungeon", type: ActivityType.Listening },
			{ name: "at Vardorvis", type: ActivityType.Playing },
			{ name: "for Virtus pieces", type: ActivityType.Playing },
			{ name: "DT2 boss guides", type: ActivityType.Watching },
			{ name: "Ancient theme", type: ActivityType.Listening },
			{ name: "at The Leviathan", type: ActivityType.Playing },
			{ name: "for ring pieces", type: ActivityType.Playing },
			{ name: "dry streak reactions", type: ActivityType.Watching },
			{ name: "Underwater", type: ActivityType.Listening },
			{ name: "at The Whisperer", type: ActivityType.Playing },
			{ name: "theory crafting videos", type: ActivityType.Watching },
			{ name: "Whispers", type: ActivityType.Listening },
			{ name: "at Duke Sucellus", type: ActivityType.Playing },
			{ name: "for magus vestige", type: ActivityType.Playing },
			{ name: "collection log videos", type: ActivityType.Watching },
			{ name: "Sucellus theme", type: ActivityType.Listening },
			{ name: "Phantom Muspah", type: ActivityType.Playing },
			{ name: "for ancient staff", type: ActivityType.Playing },
			{ name: "boss tier lists", type: ActivityType.Watching },
			{ name: "Muspah Tomb", type: ActivityType.Listening },
			{ name: "Awakened bosses", type: ActivityType.Playing },
			{ name: "for awakened orbs", type: ActivityType.Playing },
			{ name: "world record attempts", type: ActivityType.Watching },
			{ name: "Awakened theme", type: ActivityType.Listening },
			{ name: "at Vorkath", type: ActivityType.Playing },
			{ name: "for Vorki pet", type: ActivityType.Playing },
			{ name: "money making guides", type: ActivityType.Watching },
			{ name: "Fremennik Longhall", type: ActivityType.Listening },
			{ name: "Zalcano", type: ActivityType.Playing },
			{ name: "for tool seed", type: ActivityType.Playing },
			{ name: "skilling boss guides", type: ActivityType.Watching },
			{ name: "Crystal Cave", type: ActivityType.Listening },
			{ name: "Corp Beast", type: ActivityType.Playing },
			{ name: "for Ely sigil", type: ActivityType.Playing },
			{ name: "mass event highlights", type: ActivityType.Watching },
			{ name: "Spirit", type: ActivityType.Listening },
			{ name: "Cerberus", type: ActivityType.Playing },
			{ name: "for pegasian crystals", type: ActivityType.Playing },
			{ name: "pet hunting series", type: ActivityType.Watching },
			{ name: "The Slayer", type: ActivityType.Listening },
			{ name: "Hydra", type: ActivityType.Playing },
			{ name: "RNG reaction videos", type: ActivityType.Watching },
			{ name: "Karuulm Slayer", type: ActivityType.Listening },
			{ name: "at Zulrah", type: ActivityType.Playing },
			{ name: "for mutagens", type: ActivityType.Playing },
			{ name: "rotation guides", type: ActivityType.Watching },
			{ name: "Coil", type: ActivityType.Listening },
			{ name: "Scorpia", type: ActivityType.Playing },
			{ name: "Wilderness pets", type: ActivityType.Competing },
			{ name: "PvP world highlights", type: ActivityType.Watching },
			{ name: "Wilderness", type: ActivityType.Listening },
			{ name: "Maxnefien plank", type: ActivityType.Watching },
			{ name: "with Jedi", type: ActivityType.Competing },
			{ name: "to Eric yap", type: ActivityType.Listening },
			{ name: "F1...", type: ActivityType.Watching },
			{ name: "QPOH steal purples", type: ActivityType.Watching },
			{ name: "Visqo click", type: ActivityType.Watching },
			{ name: "Settled", type: ActivityType.Watching },
		];

	function updateStatus() {
		const random = activities[Math.floor(Math.random() * activities.length)];

		if (!bot.user) return;
		bot.user.setActivity(random.name, { type: random.type });
	}

	// Set initial status
	updateStatus();

	// Update every half an hour (1800000 ms)
	setInterval(updateStatus, 1800000);
}
